version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      dev-dependencies:
        patterns:
          - "actions/upload-artifact"
          - "actions/download-artifact"
          - "@types/node"
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - "@vercel/ncc"
          - "eslint"
          - "eslint-plugin-github"
          - "eslint-plugin-jsonc"
          - "eslint-plugin-prettier"
          - "prettier"
          - "typescript"
