name: Generate tag

on:
  push:
  pull_request:

jobs:
  generate-tag:
    name: Generate tag
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: "releases/v1.0.0"

      - name: Generate tag name
        uses: ./
        id: generate-tag-name

      - name: Log generated tag name
        run: echo ${{ steps.generate-tag-name.outputs.tag-name }}
